# Generated by Django 2.2.16 on 2020-09-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200930_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
