# Generated by Django 2.2.16 on 2020-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200930_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-changed_at']},
        ),
    ]
